USE [Financial]
GO

/****** Object:  Table [dbo].[SamplePortfolio]    Script Date: 5/10/2017 8:03:22 PM ******/
DROP TABLE [dbo].[SamplePortfolio]
GO

/****** Object:  Table [dbo].[SamplePortfolio]    Script Date: 5/10/2017 8:03:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SamplePortfolio](
	[As_Of_Date] [datetime] NULL,
	[Account] [varchar](15) NULL,
	[Cusip] [varchar](9) NULL,
	[InvNums] [int] NULL,
	[Account_MV] [real] NULL,
	[Issuer] [varchar](255) NULL,
	[Ticker] [varchar](55) NULL,
	[Coupon] [real] NULL,
	[Maturity] [varchar](55) NULL,
	[Price] [real] NULL,
	[Duration] [real] NULL,
	[OAS] [real] NULL,
	[YTW] [real] NULL,
	[Curr_Face] [real] NULL,
	[O-Face] [real] NULL,
	[Mkt_Val] [real] NULL,
	[PMV] [real] NULL,
	[DWE] [real] NULL,
	[Moodys] [varchar](6) NULL,
	[S&P] [varchar](6) NULL,
	[Fitch] [varchar](6) NULL,
	[Sec_Type] [varchar](55) NULL,
	[Sec_Group] [varchar](55) NULL,
	[Sec_Desc_2] [varchar](55) NULL,
	[Sprd_Dur] [real] NULL,
	[Mod_Dur] [real] NULL,
	[Effective_Dur] [real] NULL,
	[Convexity] [real] NULL,
	[YTM] [varchar](55) NULL,
	[Next_Call_Date] [varchar](55) NULL,
	[Call_Price] [varchar](55) NULL,
	[LEH_Sector] [varchar](55) NULL,
	[LEH_Sub-Sector] [varchar](55) NULL,
	[LEH_Sub-Sector_3] [varchar](55) NULL,
	[UPI_Ticker] [varchar](55) NULL,
	[UPI_Name] [varchar](255) NULL,
	[AMT_Issued] varchar(55) NULL,
	[Amt_Out] varchar(55)  NULL,
	[Book_Yield] varchar(55) NULL,
	[Book_Price] varchar(55) NULL,
	[Book_Value] varchar(55) NULL,
	[Book_G L] varchar(55) NULL,
	[WAL] varchar(55) NULL,
	[WAL_to_Worst] varchar(55) NULL,
	[Country] [varchar](55) NULL,
	[Currency] [varchar](3) NULL,
	[Market] [varchar](55) NULL,
	[ISIN] [varchar](55) NULL,
	[KRD_3M] varchar(55) NULL,
	[KRD_1Y] [real] NULL,
	[KRD_2Y] [real] NULL,
	[KRD_3Y] [real] NULL,
	[KRD_5Y] [real] NULL,
	[KRD_7Y] [real] NULL,
	[KRD_10Y] [real] NULL,
	[KRD_15Y] [real] NULL,
	[KRD_20Y] [real] NULL,
	[KRD_25Y] [real] NULL,
	[KRD_30Y] [real] NULL,
	[144a_Flag] [varchar](4) NULL,
	[Reg_Rights] [varchar](4) NULL,
	[Deriv_Flag] [varchar](4) NULL,
	[Convert_Flag] [varchar](4) NULL,
	[Top_Level_Sec_Type] [varchar](255) NULL,
	[Sec_Type_A] [varchar](55) NULL,
	[Sec_Type_B] [varchar](55) NULL,
	[Internal_Low_Rat] [varchar](10) NULL,
	[Internal_High_Rating] [varchar](6) NULL,
	[Coupon_Type] [varchar](5) NULL,
	[LEH_Rating__] [varchar](5) NULL,
	[LEH_Rating_Val] varchar(55) NULL,
	[Rating_Score] varchar(55) NULL,
	[Ratings_Combo] [varchar](55) NULL,
	[NAIC_Rating] [varchar](10) NULL,
	[Accrued_Int] varchar(55) NULL,
	[Factor] [real] NULL,
	[Flat_MV] [real] NULL,
	[Brokers] [varchar](255) NULL,
	[Issue_Date] varchar(55) NULL,
	[Prin_Begin_Date] varchar(55) NULL,
	[Lead_Manager] [varchar](55) NULL,
	[Liquidity_Indic] [varchar](4) NULL,
	[Min_Lot_Size] [varchar](255) NULL,
	[Min_Trd_Size] [varchar](255) NULL,
	[Analyst] [varchar](55) NULL,
	[Bucket] [varchar](255) NULL,
	[PaymentRank] [varchar](55) NULL,
	[ModDurToWorst] varchar(50) NULL,
	[BaseToUSD] [real] NULL,
	[AccruedInterest] [int] NULL,
	[PurchaseDate] varchar(50) NULL,
	[PurchasePrice] varchar(50) NULL,
	[NextCouponDate] varchar(50) NULL,
	[HighYieldDuration] varchar(50) NULL,
	[LoanXId] [varchar](55) NULL,
	[AladdinFileSetTypeID] [varchar](4) NULL,
	[Id] [int] NULL,
	[Stat_Book_Yield] [real] NULL,
	[Stat_Book_Price] [real] NULL,
	[Stat_Book_Value] varchar(55) NULL,
	[Stat_Book_G L] [varchar](55) NULL,
	[AccountRRP] [varchar](55) NULL,
	[AccountMVexRRP] [real] NULL,
	[PMVexRRP] [real] NULL,
	[DWEexRRP] [real] NULL,
	[UsdMktValueCalculated] [real] NULL,
	[Identifier] [varchar](55) NULL,
	[CountryOfRisk] [varchar](55) NULL,
	[CountryOfMarket] [varchar](55) NULL,
	[CountryOfIssue] [varchar](55) NULL,
	[ModelOad] [varchar](55) NULL,
	[Account_MV_USD] [real] NULL,
	[FLAT_MV_USD] [real] NULL,
	[AccruedInterest_USD] [real] NULL,
	[AccruedInt_USD] [real] NULL,
	[AccountMVexRRP_USD] [real] NULL,
	[PMVexRRP_USD] [varchar](55) NULL
) ON [PRIMARY]
GO


